//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Default, Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "Notebooks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub notebook_name: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::notebook_notes::Entity")]
    NotebookNotes,
}

impl Related<super::notebook_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotebookNotes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
