//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::note_tags::Entity as NoteTags;
pub use super::notebook_notes::Entity as NotebookNotes;
pub use super::notebooks::Entity as Notebooks;
pub use super::notes::Entity as Notes;
pub use super::tags::Entity as Tags;
