//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "Collections")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub collection_name: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_notebooks::Entity")]
    CollectionNotebooks,
}

impl Related<super::collection_notebooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionNotebooks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
