//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "CollectionNotebooks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub collection_id: i64,
    pub notebook_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::collections::Entity",
        from = "Column::CollectionId",
        to = "super::collections::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Collections,
    #[sea_orm(
        belongs_to = "super::notebooks::Entity",
        from = "Column::NotebookId",
        to = "super::notebooks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Notebooks,
}

impl Related<super::collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Collections.def()
    }
}

impl Related<super::notebooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notebooks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
