//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "Tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub tag_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::note_tags::Entity")]
    NoteTags,
}

impl Related<super::note_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NoteTags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
